/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import clasesprincipales.Subtipo;
import clasesprincipales.Tipo;
import controlador.JtreeControl;
import java.awt.Component;
import java.awt.Font;
import java.util.List;
import java.util.Map;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;

public class Categoria1 extends javax.swing.JPanel {
    private final JtreeControl jtreeControl = new JtreeControl();
    
  
    public Categoria1() {
        initComponents();
        poblarJTree(jTreeRepuestos, 248712); 
        poblarJTree(jTreeLubri, 248717); 
        poblarJTree(jTreeAcces, 248747);
        personalizarJTreeSinIconos(jTreeRepuestos);
        personalizarJTreeSinIconos(jTreeAcces);
        personalizarJTreeSinIconos(jTreeLubri);
    }
   private void poblarJTree(JTree tree, int idCategoria) {
    String nombreCategoria = switch (idCategoria) {
        case 248712 -> "Repuestos";
        case 248717 -> "Accesorios";
        case 248747 -> "Lubricantes";
        default -> "Categoría";
    };

    DefaultMutableTreeNode raiz = new DefaultMutableTreeNode(nombreCategoria);

    Map<Tipo, List<Subtipo>> jerarquia = jtreeControl.obtenerJerarquiaTiposYSubtipos(idCategoria);

    for (Map.Entry<Tipo, List<Subtipo>> entry : jerarquia.entrySet()) {
        Tipo tipo = entry.getKey();
        DefaultMutableTreeNode nodoTipo = new DefaultMutableTreeNode(tipo); 

        for (Subtipo subtipo : entry.getValue()) {
            DefaultMutableTreeNode nodoSubtipo = new DefaultMutableTreeNode(subtipo); // ✅
            nodoTipo.add(nodoSubtipo);
        }

        raiz.add(nodoTipo);
    }

    tree.setModel(new DefaultTreeModel(raiz));
}
   private void personalizarJTreeSinIconos(JTree tree) {
    tree.setCellRenderer(new DefaultTreeCellRenderer() {
        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value,
                boolean sel, boolean expanded, boolean leaf, int row, boolean hasFocus) {

            super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);

            // Elimina todos los íconos visuales
            setOpenIcon(null);
            setClosedIcon(null);
            setLeafIcon(null);

            return this;
        }
    });

    // Opcional: mejora el estilo visual general
    tree.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    tree.setRowHeight(22);
}

    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanelRound2 = new GUI.JPanelRound();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanelRound6 = new GUI.JPanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTreeLubri = new javax.swing.JTree();
        jPanelRound7 = new GUI.JPanelRound();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTreeAcces = new javax.swing.JTree();
        jPanelRound8 = new GUI.JPanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTreeRepuestos = new javax.swing.JTree();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanelRound2.setBackground(new java.awt.Color(122, 123, 179));
        jPanelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 253, 255));
        jLabel3.setText("Accesorios");
        jPanelRound2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 253, 255));
        jLabel2.setText("Repuestos");
        jPanelRound2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 120, 30));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 253, 255));
        jLabel4.setText("Lubricantes");
        jPanelRound2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download.jpeg"))); // NOI18N
        jLabel5.setOpaque(true);
        jPanelRound2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download.jpeg"))); // NOI18N
        jPanelRound2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 240, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download.jpeg"))); // NOI18N
        jPanelRound2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download.jpeg"))); // NOI18N
        jPanelRound2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 190, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/download.jpeg"))); // NOI18N
        jPanelRound2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 190, 70));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jPanelRound6.setBackground(new java.awt.Color(19, 25, 113));

        jTreeLubri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeLubriMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTreeLubri);

        javax.swing.GroupLayout jPanelRound6Layout = new javax.swing.GroupLayout(jPanelRound6);
        jPanelRound6.setLayout(jPanelRound6Layout);
        jPanelRound6Layout.setHorizontalGroup(
            jPanelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRound6Layout.setVerticalGroup(
            jPanelRound6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        jPanelRound7.setBackground(new java.awt.Color(19, 25, 113));

        jTreeAcces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeAccesMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(jTreeAcces);

        javax.swing.GroupLayout jPanelRound7Layout = new javax.swing.GroupLayout(jPanelRound7);
        jPanelRound7.setLayout(jPanelRound7Layout);
        jPanelRound7Layout.setHorizontalGroup(
            jPanelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRound7Layout.setVerticalGroup(
            jPanelRound7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        jPanelRound8.setBackground(new java.awt.Color(19, 25, 113));

        jTreeRepuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTreeRepuestosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTreeRepuestos);

        javax.swing.GroupLayout jPanelRound8Layout = new javax.swing.GroupLayout(jPanelRound8);
        jPanelRound8.setLayout(jPanelRound8Layout);
        jPanelRound8Layout.setHorizontalGroup(
            jPanelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelRound8Layout.setVerticalGroup(
            jPanelRound8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jPanelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jPanelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jPanelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelRound8, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelRound6, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanelRound7, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeRepuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeRepuestosMouseClicked
    if (evt.getClickCount() == 2) { // Solo actúa en doble clic
        TreePath selPath = jTreeRepuestos.getPathForLocation(evt.getX(), evt.getY());

        if (selPath != null) {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selPath.getLastPathComponent();
            Object userObj = selectedNode.getUserObject();

            if (userObj instanceof Tipo tipoSeleccionado) {
                VerCategoria dialog = new VerCategoria(null, true, "tipo", tipoSeleccionado.getIdTipo());
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            } else if (userObj instanceof Subtipo subtipoSeleccionado) {
                VerCategoria dialog = new VerCategoria(null, true, "subtipo", subtipoSeleccionado.getIdSubtipo());
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        }
    }

    }//GEN-LAST:event_jTreeRepuestosMouseClicked

    private void jTreeLubriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeLubriMouseClicked
        if (evt.getClickCount() == 2) { // Solo actúa en doble clic
        TreePath selPath = jTreeLubri.getPathForLocation(evt.getX(), evt.getY());

        if (selPath != null) {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selPath.getLastPathComponent();
            Object userObj = selectedNode.getUserObject();

            if (userObj instanceof Tipo tipoSeleccionado) {
                VerCategoria dialog = new VerCategoria(null, true, "tipo", tipoSeleccionado.getIdTipo());
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            } else if (userObj instanceof Subtipo subtipoSeleccionado) {
                VerCategoria dialog = new VerCategoria(null, true, "subtipo", subtipoSeleccionado.getIdSubtipo());
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        }
     }
    }//GEN-LAST:event_jTreeLubriMouseClicked

    private void jTreeAccesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTreeAccesMouseClicked
        if (evt.getClickCount() == 2) { 
        TreePath selPath = jTreeAcces.getPathForLocation(evt.getX(), evt.getY());

        if (selPath != null) {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selPath.getLastPathComponent();
            Object userObj = selectedNode.getUserObject();

            if (userObj instanceof Tipo tipoSeleccionado) {
                VerCategoria dialog = new VerCategoria(null, true, "tipo", tipoSeleccionado.getIdTipo());
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            } else if (userObj instanceof Subtipo subtipoSeleccionado) {
                VerCategoria dialog = new VerCategoria(null, true, "subtipo", subtipoSeleccionado.getIdSubtipo());
                dialog.setLocationRelativeTo(null);
                dialog.setVisible(true);
            }
        }
    }
    }//GEN-LAST:event_jTreeAccesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private GUI.JPanelRound jPanelRound2;
    private GUI.JPanelRound jPanelRound6;
    private GUI.JPanelRound jPanelRound7;
    private GUI.JPanelRound jPanelRound8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTree jTreeAcces;
    private javax.swing.JTree jTreeLubri;
    private javax.swing.JTree jTreeRepuestos;
    // End of variables declaration//GEN-END:variables
}
