/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import java.util.Set;
import seguridad.Permiso;

/**
 *
 * @author user
 */
public class Dashboard1 extends javax.swing.JPanel {
    public void aplicarPermisos(Set<Permiso> permisos) {
    btnHISTORIAL.setVisible(permisos.contains(Permiso.HISTORIAL_VER));
    btnstock1.setVisible(permisos.contains(Permiso.STOCK_VER)|| permisos.contains(Permiso.STOCK_ALERTA));
    btnFACTURA.setVisible(permisos.contains(Permiso.FACTURA_VER)|| permisos.contains(Permiso.FACTURA_GESTIONAR));
}

    /**
     * Creates new form Dashboard1
     */
    public Dashboard1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        btnHISTORIAL = new javax.swing.JButton();
        btnstock1 = new javax.swing.JButton();
        btnFACTURA = new javax.swing.JButton();

        Contenedor.setBackground(new java.awt.Color(204, 204, 204));

        btnHISTORIAL.setBackground(new java.awt.Color(255, 153, 51));
        btnHISTORIAL.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        btnHISTORIAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-time-machine-32.png"))); // NOI18N
        btnHISTORIAL.setText("Historial de movimientos");
        btnHISTORIAL.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHISTORIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHISTORIALActionPerformed(evt);
            }
        });

        btnstock1.setBackground(new java.awt.Color(255, 153, 51));
        btnstock1.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        btnstock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-package-32.png"))); // NOI18N
        btnstock1.setText("Stock Bajo");
        btnstock1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnstock1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstock1ActionPerformed(evt);
            }
        });

        btnFACTURA.setBackground(new java.awt.Color(255, 153, 51));
        btnFACTURA.setFont(new java.awt.Font("Leelawadee UI", 1, 16)); // NOI18N
        btnFACTURA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-activity-history-40.png"))); // NOI18N
        btnFACTURA.setText("Factura");
        btnFACTURA.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnFACTURA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFACTURAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnstock1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnHISTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnFACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHISTORIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstock1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFACTURA, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(589, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHISTORIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHISTORIALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHISTORIALActionPerformed

    private void btnstock1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstock1ActionPerformed
    VerStockBajo dialog = new VerStockBajo(null, true); // Sin padre
    dialog.setVisible(true);
    }//GEN-LAST:event_btnstock1ActionPerformed

    private void btnFACTURAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFACTURAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFACTURAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private javax.swing.JButton btnFACTURA;
    private javax.swing.JButton btnHISTORIAL;
    private javax.swing.JButton btnstock1;
    // End of variables declaration//GEN-END:variables
}
