/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;



/**
 *
 * @author user
 */
public class Devoluciones1 extends javax.swing.JPanel {
    public Devoluciones1() {
        initComponents();    
    }
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor2 = new javax.swing.JPanel();
        jPanelRound1 = new GUI.JPanelRound();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDevoluciones = new javax.swing.JTable();
        rSButtonMaterialIconDos1 = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnEliminarDE = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnactualizarDE = new RSMaterialComponent.RSButtonMaterialIconDos();
        barraBusqueda = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        Contenedor2.setBackground(new java.awt.Color(255, 255, 255));

        jPanelRound1.setBackground(new java.awt.Color(198, 199, 232));
        jPanelRound1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel1.setText("Devoluciones");

        tablaDevoluciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "#", "IDProducto", "Proovedor", "Cantidad", "Fecha de  Devolución", "Motivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDevoluciones);
        if (tablaDevoluciones.getColumnModel().getColumnCount() > 0) {
            tablaDevoluciones.getColumnModel().getColumn(0).setResizable(false);
            tablaDevoluciones.getColumnModel().getColumn(1).setResizable(false);
            tablaDevoluciones.getColumnModel().getColumn(2).setResizable(false);
            tablaDevoluciones.getColumnModel().getColumn(3).setResizable(false);
            tablaDevoluciones.getColumnModel().getColumn(5).setResizable(false);
        }

        rSButtonMaterialIconDos1.setBackground(new java.awt.Color(29, 37, 172));
        rSButtonMaterialIconDos1.setText("Agregar");
        rSButtonMaterialIconDos1.setForegroundIcon(new java.awt.Color(253, 129, 4));
        rSButtonMaterialIconDos1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD);
        rSButtonMaterialIconDos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMaterialIconDos1ActionPerformed(evt);
            }
        });

        btnEliminarDE.setBackground(new java.awt.Color(29, 37, 172));
        btnEliminarDE.setText("Eliminar");
        btnEliminarDE.setForegroundIcon(new java.awt.Color(253, 129, 4));
        btnEliminarDE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DELETE);
        btnEliminarDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDEActionPerformed(evt);
            }
        });

        btnactualizarDE.setBackground(new java.awt.Color(29, 37, 172));
        btnactualizarDE.setText("Actualizar");
        btnactualizarDE.setForegroundIcon(new java.awt.Color(253, 129, 4));
        btnactualizarDE.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EDIT);
        btnactualizarDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarDEActionPerformed(evt);
            }
        });

        barraBusqueda.setForeground(new java.awt.Color(185, 182, 167));
        barraBusqueda.setText("Buscar...");
        barraBusqueda.setOpaque(true);
        barraBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barraBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 984, Short.MAX_VALUE))
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnactualizarDE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(btnEliminarDE, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(rSButtonMaterialIconDos1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barraBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizarDE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarDE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSButtonMaterialIconDos1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Contenedor2Layout = new javax.swing.GroupLayout(Contenedor2);
        Contenedor2.setLayout(Contenedor2Layout);
        Contenedor2Layout.setHorizontalGroup(
            Contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Contenedor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Contenedor2Layout.setVerticalGroup(
            Contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Contenedor2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDEActionPerformed

    private void btnactualizarDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarDEActionPerformed
        // TODO add your handling code here:
        ActualizarDevolucion AD = new  ActualizarDevolucion(); 
         AD.setSize(840, 440); 
         AD.setLocationRelativeTo(null); 
         AD.setVisible(true); 
    }//GEN-LAST:event_btnactualizarDEActionPerformed

    private void rSButtonMaterialIconDos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMaterialIconDos1ActionPerformed
        // TODO add your handling code here:
        AgregarDevolucion A = new AgregarDevolucion(); 
         A.setSize(787, 500); 
         A.setLocationRelativeTo(null); 
         A.setVisible(true); 
    }//GEN-LAST:event_rSButtonMaterialIconDos1ActionPerformed

    private void barraBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barraBusquedaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_barraBusquedaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor2;
    private javax.swing.JTextField barraBusqueda;
    private RSMaterialComponent.RSButtonMaterialIconDos btnEliminarDE;
    private RSMaterialComponent.RSButtonMaterialIconDos btnactualizarDE;
    private javax.swing.JLabel jLabel1;
    private GUI.JPanelRound jPanelRound1;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSButtonMaterialIconDos rSButtonMaterialIconDos1;
    private javax.swing.JTable tablaDevoluciones;
    // End of variables declaration//GEN-END:variables
}
