/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import clasesprincipales.Usuario;
import java.awt.BorderLayout;
import java.util.Set;
import seguridad.Permiso;


/**
 *
 * @author user
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private Usuario usuario;
    private Dashboard1 dashboard;

    public MenuPrincipal(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        aplicarPermisos();
        mostrarDashboard();
    }

    private void mostrarDashboard() {
        dashboard = new Dashboard1();
        dashboard.setSize(1255, 900);
        dashboard.setLocation(0, 0);
        Contenedor.removeAll();
        Contenedor.add(dashboard, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();

        
        dashboard.aplicarPermisos(usuario.getPermisos());
    }

    private void aplicarPermisos() {
        Set<Permiso> permisos = usuario.getPermisos();

        btnUSU.setVisible(permisos.contains(Permiso.USUARIOS_VER));
        btnCONFI.setVisible(permisos.contains(Permiso.CONFIGURACION_VER));
        btproductos.setVisible(permisos.contains(Permiso.PRODUCTOS_VER) || permisos.contains(Permiso.PRODUCTOS_GESTIONAR));
        btnPRO.setVisible(permisos.contains(Permiso.PROVEEDORES_VER));
        btnCate.setVisible(permisos.contains(Permiso.CATEGORIAS_VER));
        btnDEVOL.setVisible(permisos.contains(Permiso.DEVOLUCIONES_VER));

        // Aquí solo aplicas los permisos para los elementos del MenuPrincipal
    }



    /**
     * Creates new form MenuPrincipal
     */
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanelRound1 = new GUI.JPanelRound();
        btnDASH = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnUSU = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnCONFI = new RSMaterialComponent.RSButtonMaterialIconDos();
        btproductos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnPRO = new RSMaterialComponent.RSButtonMaterialIconDos();
        jLabel1 = new javax.swing.JLabel();
        btnCate = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnDEVOL = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnACER = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSA = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelRound2 = new GUI.JPanelRound();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contenedor.setBackground(new java.awt.Color(204, 204, 204));
        Contenedor.setPreferredSize(new java.awt.Dimension(890, 682));

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 1, 2)));

        jPanelRound1.setBackground(new java.awt.Color(19, 25, 113));

        btnDASH.setBackground(new java.awt.Color(19, 25, 113));
        btnDASH.setText("Dashboard");
        btnDASH.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btnDASH.setForegroundIcon(new java.awt.Color(247, 129, 7));
        btnDASH.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        btnDASH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDASHActionPerformed(evt);
            }
        });

        btnUSU.setBackground(new java.awt.Color(19, 25, 113));
        btnUSU.setText("Usuarios");
        btnUSU.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btnUSU.setForegroundIcon(new java.awt.Color(247, 129, 7));
        btnUSU.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ACCOUNT_CIRCLE);
        btnUSU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUSUActionPerformed(evt);
            }
        });

        btnCONFI.setBackground(new java.awt.Color(19, 25, 113));
        btnCONFI.setText("Configuración");
        btnCONFI.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btnCONFI.setForegroundIcon(new java.awt.Color(247, 129, 7));
        btnCONFI.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BUBBLE_CHART);

        btproductos.setBackground(new java.awt.Color(19, 25, 113));
        btproductos.setText("Productos");
        btproductos.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btproductos.setForegroundIcon(new java.awt.Color(247, 129, 7));
        btproductos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ADD_CIRCLE);
        btproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btproductosActionPerformed(evt);
            }
        });

        btnPRO.setBackground(new java.awt.Color(19, 25, 113));
        btnPRO.setText("Proveedores");
        btnPRO.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btnPRO.setForegroundIcon(new java.awt.Color(247, 129, 7));
        btnPRO.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LOCAL_LIBRARY);
        btnPRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPROActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(242, 255, 249));
        jLabel1.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 247));
        jLabel1.setText("Mantenimiento");

        btnCate.setBackground(new java.awt.Color(19, 25, 113));
        btnCate.setText("Categorias");
        btnCate.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btnCate.setForegroundIcon(new java.awt.Color(247, 129, 7));
        btnCate.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.LAYERS);
        btnCate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCateActionPerformed(evt);
            }
        });

        btnDEVOL.setBackground(new java.awt.Color(19, 25, 113));
        btnDEVOL.setText("Devoluciones");
        btnDEVOL.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btnDEVOL.setForegroundIcon(new java.awt.Color(247, 129, 7));
        btnDEVOL.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SWAP_HORIZ);
        btnDEVOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDEVOLActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(242, 255, 249));
        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 247));
        jLabel3.setText("Menú Principal");

        btnACER.setBackground(new java.awt.Color(19, 25, 113));
        btnACER.setText("Acerca de");
        btnACER.setBackgroundHover(new java.awt.Color(135, 138, 212));
        btnACER.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HELP);
        btnACER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACERActionPerformed(evt);
            }
        });

        btnSA.setBackground(new java.awt.Color(19, 25, 113));
        btnSA.setText("Salir");
        btnSA.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        btnSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRound1Layout = new javax.swing.GroupLayout(jPanelRound1);
        jPanelRound1.setLayout(jPanelRound1Layout);
        jPanelRound1Layout.setHorizontalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addComponent(btnDASH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUSU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCONFI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btproductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPRO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDEVOL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnACER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator3)
                    .addGroup(jPanelRound1Layout.createSequentialGroup()
                        .addGroup(jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 110, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelRound1Layout.setVerticalGroup(
            jPanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDASH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDEVOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btproductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUSU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCONFI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnACER, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelRound2.setBackground(new java.awt.Color(30, 34, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imagen_2024-11-21_165706495.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel2.setFont(new java.awt.Font("Impact", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(253, 129, 4));
        jLabel2.setText("Inventario ");

        jLabel5.setFont(new java.awt.Font("Impact", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Full Motor");

        javax.swing.GroupLayout jPanelRound2Layout = new javax.swing.GroupLayout(jPanelRound2);
        jPanelRound2.setLayout(jPanelRound2Layout);
        jPanelRound2Layout.setHorizontalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRound2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelRound2Layout.setVerticalGroup(
            jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Contenedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCateActionPerformed
        // TODO add your handling code here:
        btnCate.setSelected(true);
        btnDASH.setSelected(false);
        btnDEVOL.setSelected(false);
        btnPRO.setSelected(false);
        btproductos.setSelected(false);
        Categoria1 C = new Categoria1();
        C.setSize(1019, 756);
        C.setLocation(0, 0);

        Contenedor.removeAll(); 
        Contenedor.add(C, BorderLayout.CENTER); 
        Contenedor.revalidate(); 
        Contenedor.repaint(); 
    }//GEN-LAST:event_btnCateActionPerformed

    private void btnACERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnACERActionPerformed

    private void btnSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_btnSAActionPerformed

    private void btnDASHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDASHActionPerformed
        // TODO add your handling code here:
        btnDASH.setSelected(true);
        btnDEVOL.setSelected(false);
        btnCate.setSelected(false);
        btnPRO.setSelected(false);
        btproductos.setSelected(false);
        btnUSU.setSelected(false);
        Dashboard1 d=new Dashboard1 ();
        d.setSize(1019, 756);
        d.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(d, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_btnDASHActionPerformed

    private void btnDEVOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDEVOLActionPerformed
        // TODO add your handling code here:
        btnDEVOL.setSelected(true);
        btnDASH.setSelected(false);
        btnCate.setSelected(false);
        btnPRO.setSelected(false);
        btnUSU.setSelected(false);
        btproductos.setSelected(false);
        Devoluciones1 D=new Devoluciones1 ();
        D.setSize(1019, 756);
        D.setLocation(0,0);
        
        Contenedor.removeAll();
        Contenedor.add(D, BorderLayout.CENTER);
        Contenedor.revalidate();
        Contenedor.repaint();
    }//GEN-LAST:event_btnDEVOLActionPerformed

    private void btnPROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPROActionPerformed
        // TODO add your handling code here:
        btnPRO.setSelected(true);
        btnDASH.setSelected(false);
        btnDEVOL.setSelected(false);
        btnCate.setSelected(false);
        btproductos.setSelected(false);
        btnUSU.setSelected(false);
        Proovedores1 P = new Proovedores1();
        P.setSize(1019, 756);
        P.setLocation(0, 0);

        Contenedor.removeAll(); 
        Contenedor.add(P, BorderLayout.CENTER); 
        Contenedor.revalidate(); 
        Contenedor.repaint();
    }//GEN-LAST:event_btnPROActionPerformed

    private void btproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btproductosActionPerformed
        // TODO add your handling code here:
        btproductos.setSelected(true);
        btnPRO.setSelected(false);
        btnDASH.setSelected(false);
        btnDEVOL.setSelected(false);
        btnCate.setSelected(false);
        btnUSU.setSelected(false);
        ProductosGui P = new ProductosGui();
        P.setSize(1019, 756);
        P.setLocation(0, 0);

        Contenedor.removeAll(); 
        Contenedor.add(P, BorderLayout.CENTER); 
        Contenedor.revalidate(); 
        Contenedor.repaint();
        
    }//GEN-LAST:event_btproductosActionPerformed

    private void btnUSUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUSUActionPerformed
        // TODO add your handling code here:
        btnUSU.setSelected(true);
        btproductos.setSelected(false);
        btnPRO.setSelected(false);
        btnDASH.setSelected(false);
        btnDEVOL.setSelected(false);
        btnCate.setSelected(false);
        ProductosGui P = new ProductosGui();
        P.setSize(1019, 756);
        P.setLocation(0, 0);

        Contenedor.removeAll(); 
        Contenedor.add(P, BorderLayout.CENTER); 
        Contenedor.revalidate(); 
        Contenedor.repaint();
    }//GEN-LAST:event_btnUSUActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    private RSMaterialComponent.RSButtonMaterialIconDos btnACER;
    private RSMaterialComponent.RSButtonMaterialIconDos btnCONFI;
    private RSMaterialComponent.RSButtonMaterialIconDos btnCate;
    private RSMaterialComponent.RSButtonMaterialIconDos btnDASH;
    private RSMaterialComponent.RSButtonMaterialIconDos btnDEVOL;
    private RSMaterialComponent.RSButtonMaterialIconDos btnPRO;
    private RSMaterialComponent.RSButtonMaterialIconDos btnSA;
    private RSMaterialComponent.RSButtonMaterialIconDos btnUSU;
    private RSMaterialComponent.RSButtonMaterialIconDos btproductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private GUI.JPanelRound jPanelRound1;
    private GUI.JPanelRound jPanelRound2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
